name: Execute Command on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger option

jobs:
  run-on-ec2:
    runs-on: ubuntu-latest  # GitHub-hosted Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
        shell: bash

      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          cp scripts/aws-credentials.txt ~/.aws/credentials
        shell: bash

      - name: Add SSH Private Key
        run: |
          mkdir -p ~/.ssh
          cp scripts/aws-key.pem ~/.ssh/aws-key.pem
          chmod 600 ~/.ssh/aws-key.pem
        shell: bash

      - name: Execute PowerShell Script
        run: pwsh scripts/fetch-config.ps1
        shell: pwsh

      - name: Upload Output to S3
        run: |
          aws s3 cp output s3://os-comparison-bucket/ --recursive
        shell: bash

      - name: Trigger AWS Lambda for Comparison
        run: |
          aws lambda invoke --function-name comparefiles --payload '{}' response.json
        shell: bash
