name: AWS EC2 Automation

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update AWS CLI (Non-Interactive)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip   # Force overwrite without prompt
          sudo ./aws/install --update
          aws --version

      - name: Configure AWS CLI Profile
        run: bash scripts/aws-profile-setup.sh

      - name: Get EC2 Public IPs
        run: |
          instance_ids=$(cat serverlist.txt)
          public_ips=$(aws ec2 describe-instances --instance-ids $instance_ids --query "Reservations[*].Instances[*].PublicIpAddress" --output text --region us-east-1)
          echo "PUBLIC_IPS=$public_ips" >> $GITHUB_ENV
        shell: bash

      - name: Set up SSH Key for EC2 Access
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Execute PowerShell Script on EC2
        run: |
          for ip in $PUBLIC_IPS; do
            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$ip "powershell -File ~/fetch-config.ps1"
          done

      - name: Upload Output to S3
        run: |
          for ip in $PUBLIC_IPS; do
            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$ip "aws s3 cp ~/output.txt s3://os-comparison-bucket/output-$ip.txt --profile my-profile"
          done
