name: EC2 Automation Workflow

on:
  push:
    branches:
      - main # Change this based on your repo branch

jobs:
  automate-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI Profile
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = YOUR_ACCESS_KEY" >> ~/.aws/credentials
          echo "aws_secret_access_key = YOUR_SECRET_KEY" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
          chmod 600 ~/.aws/credentials

      - name: Install AWS CLI & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq

      - name: Get Instance Public IPs
        id: get-ec2-ips
        run: |
          instance_ids=$(cat serverlist.txt)
          public_ips=$(aws ec2 describe-instances --instance-ids $instance_ids --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
          echo "PUBLIC_IPS=$public_ips" >> $GITHUB_ENV

      - name: Set up SSH Key for EC2 Access
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Execute PowerShell Script on EC2
        run: |
          for ip in $PUBLIC_IPS; do
            ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$ip "pwsh -File /home/ec2-user/fetch-config.ps1"
          done

      - name: Upload Output to S3
        run: |
          for ip in $PUBLIC_IPS; do
            scp -i private_key.pem ec2-user@$ip:/home/ec2-user/output.txt ./output_$ip.txt
            aws s3 cp ./output_$ip.txt s3://os-comparison-bucket/output_$ip.txt
          done

      - name: Trigger AWS Lambda Function
        run: |
          aws lambda invoke --function-name compare-files --payload '{}' response.json
          cat response.json
