name: AWS EC2 SSH Execution

on:
  push:
    branches:
      - main

jobs:
  ssh-execution:
    runs-on: windows-latest # Required for PowerShell & Plink

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install PuTTY
        run: |
          choco install putty -y
        shell: pwsh

      - name: Run PowerShell SSH Script
        shell: pwsh
        run: pwsh scripts/fetch-config.ps1
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

      - name: Upload Output Files
        uses: actions/upload-artifact@v3
        with:
          name: ssh-output
          path: scripts/*-output.txt
