name: EC2 Remote Execution & AWS Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  execute-on-ec2:
    runs-on: windows-latest  # Use Windows runner for PowerShell compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up AWS Credentials
        run: |
          mkdir -p $HOME\.aws
          cp scripts/aws-credentials.txt $HOME\.aws\credentials
        shell: bash

      - name: Install AWS CLI
        run: |
          Invoke-WebRequest -Uri "https://awscli.amazonaws.com/AWSCLIV2.msi" -OutFile "AWSCLIV2.msi"
          Start-Process msiexec.exe -ArgumentList '/i AWSCLIV2.msi /quiet /norestart' -Wait
        shell: pwsh

      - name: Install PuTTY (Plink)
        run: |
          choco install putty -y
        shell: pwsh

      - name: Execute PowerShell Script on EC2
        run: pwsh scripts/fetch-config.ps1
        shell: pwsh

      - name: Upload Output Files to S3
        run: |
          aws s3 cp output s3:/os-comparison-bucket/ --recursive
        shell: bash

      - name: Trigger AWS Lambda for Comparison
        run: |
          aws lambda invoke --function-name comparefiles --payload '{}' response.json
        shell: bash
