name: EC2 Automation Workflow

on:
  push:
    branches:
      - main # Change this based on your repo branch

jobs:
  automate-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Update AWS CLI (Non-Interactive)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip   # Force overwrite without prompt
          sudo ./aws/install --update
          aws --version

      - name: Get EC2 Public IPs
        run: |
          instance_ids=$(cat serverlist.txt)
          public_ips=$(aws ec2 describe-instances --instance-ids $instance_ids --query "Reservations[*].Instances[*].PublicIpAddress" --output text --region us-east-1)
          echo "PUBLIC_IPS=$public_ips" >> $GITHUB_ENV
        shell: /usr/bin/bash

      - name: Set up SSH Key for EC2 Access
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Execute PowerShell Script on EC2
        run: |
          for ip in $PUBLIC_IPS; do
            ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$ip "pwsh -File /home/ec2-user/fetch-config.ps1"
          done

      - name: Upload Output to S3
        run: |
          for ip in $PUBLIC_IPS; do
            scp -i private_key.pem ec2-user@$ip:/home/ec2-user/output.txt ./output_$ip.txt
            aws s3 cp ./output_$ip.txt s3://os-comparison-bucket/output_$ip.txt
          done

      - name: Trigger AWS Lambda Function
        run: |
          aws lambda invoke --function-name compare-files --payload '{}' response.json
          cat response.json
