name: Execute PowerShell on AWS EC2 via SSM

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest # GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI Profile
        run: ./aws-profile-setup.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Install PowerShell
        run: |
          sudo apt update
          sudo apt install -y powershell
          pwsh --version

      - name: Execute PowerShell Script via AWS SSM
        run: pwsh ./fetch-config.ps1
